id: P0680C678
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: bo
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    0d1aa698e5004d29b174afd49337ff86:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    1d10a12f5fad4369bd3d5840babba95d:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    3e26c336c9ec4abe95dbd4a613b1af0e:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    1c22a4353b1f48198abf6081f64320a9:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    5f48c1f825d5457d9756a9ebf5c71333:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    af9e21e1ce6140bda5da9f688a296196:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    711b808243e54a7eb444dbdb488a6a9d:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    fb0f094ca0c94abeb56a3ea5914b8c31:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    007b42bb614f40ae8b3c0363d7662e31:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    b759e2e4118d4c1a901601cab7fe5854:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    4d53ac15e6764585a5d0b8a971d70996:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    76c681df755c44f7a070603d9aedda83:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.693601'
last_modified_at: '2022-02-28T23:00:39.693604'
statistics:
  total_words: 13486
  total_non_words: 1534
quality:
  non_words_ratio: 0.11
